name: Generate Docs (README + Wiki)

on:
  workflow_dispatch:
    inputs:
      include-template:
        description: 'Include template directories'
        required: false
        default: 'false'
  push:
    branches: ['main']

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: false

jobs:
  docs:
    name: Build docs with OpenAI and open PR
    runs-on: ubuntu-latest

    steps:
      - name: Check required secret
        id: secretcheck
        run: |
          if [ -z "${{ secrets.OPENAI_API_KEY }}" ]; then
            echo "OPENAI_API_KEY is missing – skipping docs generation."
            echo "missing=true" >> "$GITHUB_OUTPUT"
          else
            echo "missing=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Stop early if secret is missing
        if: steps.secretcheck.outputs.missing == 'true'
        run: echo "::notice title=Docs skipped::No OPENAI_API_KEY secret configured."

      - name: Checkout repo
        if: steps.secretcheck.outputs.missing == 'false'
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node (for consistency)
        if: steps.secretcheck.outputs.missing == 'false'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install jq
        if: steps.secretcheck.outputs.missing == 'false'
        run: sudo apt-get install -y jq

      - name: Install dependencies
        if: steps.secretcheck.outputs.missing == 'false'
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Collect repository context
        if: steps.secretcheck.outputs.missing == 'false'
        run: |
          set -euo pipefail
          FLAG=${{ github.event.inputs.include-template == 'true' && '--all' || '--user-only' }}
          node scripts/generate-docs.mjs $FLAG
          echo "Context size:" && wc -c repo_context.txt || true

      - name: Generate README with OpenAI (scripted)
        if: steps.secretcheck.outputs.missing == 'false'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: bash scripts/ai-readme.sh

      - name: Build Wiki from code comments
        if: steps.secretcheck.outputs.missing == 'false'
        run: npm run docs:wiki

      - name: Format README and Wiki
        if: steps.secretcheck.outputs.missing == 'false'
        run: npm run fmt README.md docs/wiki

      - name: Push Wiki
        if: steps.secretcheck.outputs.missing == 'false'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail

          # 0) Wiki-Inhalt vorhanden?
          if [ ! -d docs/wiki ] || [ -z "$(ls -A docs/wiki)" ]; then
            echo "No wiki content to push."
            exit 0
          fi

          WIKI_URL="https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.wiki.git"

          git config --global user.name  "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # 1) Wiki-Repo frisch klonen und sicherstellen, dass origin auf das Wiki zeigt
          rm -rf wiki-repo
          git clone "$WIKI_URL" wiki-repo
          git -C wiki-repo remote set-url origin "$WIKI_URL"

          # 2) Default-Branch (master/main) ermitteln
          DEFAULT_BRANCH="$(git -C wiki-repo remote show origin | awk '/HEAD branch/ {print $NF}')"
          if [ -z "${DEFAULT_BRANCH:-}" ]; then
            if git -C wiki-repo show-ref --verify --quiet refs/remotes/origin/master; then
              DEFAULT_BRANCH="master"
            else
              DEFAULT_BRANCH="main"
            fi
          fi
          echo "Wiki default branch detected: ${DEFAULT_BRANCH}"

          # 3) Branch auschecken (ggf. neu anlegen)
          if git -C wiki-repo show-ref --verify --quiet "refs/remotes/origin/${DEFAULT_BRANCH}"; then
            git -C wiki-repo checkout -B "${DEFAULT_BRANCH}" "origin/${DEFAULT_BRANCH}"
          else
            git -C wiki-repo checkout --orphan "${DEFAULT_BRANCH}"
            rm -rf wiki-repo/*
            git -C wiki-repo commit --allow-empty -m "init wiki"
          fi

          # 4) Inhalte spiegeln und committen
          rsync -a --delete docs/wiki/ wiki-repo/
          git -C wiki-repo add -A
          if git -C wiki-repo diff --cached --quiet; then
            echo "No wiki changes to commit."
            exit 0
          fi
          git -C wiki-repo commit -m "docs: update Wiki from workflow"

          # 5) Push: normal → bei Ablehnung fetch+rebase → retry → force-with-lease
          echo "Pushing to ${DEFAULT_BRANCH}..."
          if ! git -C wiki-repo push origin HEAD:${DEFAULT_BRANCH}; then
            echo "Push rejected. Fetching and rebasing..."
            git -C wiki-repo fetch origin ${DEFAULT_BRANCH} || true
            git -C wiki-repo pull --rebase origin ${DEFAULT_BRANCH} || true
            git -C wiki-repo push origin HEAD:${DEFAULT_BRANCH} || \
              git -C wiki-repo push --force-with-lease origin HEAD:${DEFAULT_BRANCH}
          fi
          echo "✅ Wiki pushed."


      - name: Prepare docs branch (no checkout/switch)
        if: steps.secretcheck.outputs.missing == 'false'
        id: prep
        run: |
          set -euo pipefail
          BR="docs/generated-${{ github.run_id }}"
          git add README.md docs/wiki || true
          if git diff --cached --quiet; then
            echo "No doc changes detected – skipping PR."
            echo "skip_pr=true" >> "$GITHUB_OUTPUT"
          else
            echo "skip_pr=false" >> "$GITHUB_OUTPUT"
            echo "branch=$BR" >> "$GITHUB_OUTPUT"
          fi

      - name: Create Pull Request
        id: cpr
        if: steps.prep.outputs.skip_pr == 'false' && steps.secretcheck.outputs.missing == 'false'
        uses: peter-evans/create-pull-request@v6
        with:
          base: main
          branch: ${{ steps.prep.outputs.branch }}
          commit-message: 'docs: auto-generate README + Wiki'
          title: 'Automatisch generierte Doku (README + Wiki)'
          body: 'Dieser PR wurde automatisch erstellt – bitte prüfen und mergen.'
          labels: 'automation, docs'
          signoff: false
          add-paths: |
            README.md
            docs/wiki/**

      - name: Enable auto-merge (squash)
        if: steps.prep.outputs.skip_pr == 'false' && steps.secretcheck.outputs.missing == 'false'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
