name: Generate Docs (README + Wiki)

on:
  workflow_dispatch:
    inputs:
      include-template:
        description: 'Include template directories'
        required: false
        default: 'false'
  push:
    branches: ['main']

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: false

jobs:
  docs:
    name: Build docs with OpenAI and open PR
    runs-on: ubuntu-latest

    steps:
      - name: Check required secret
        id: secretcheck
        run: |
          if [ -z "${{ secrets.OPENAI_API_KEY }}" ]; then
            echo "OPENAI_API_KEY is missing – skipping docs generation."
            echo "missing=true" >> "$GITHUB_OUTPUT"
          else
            echo "missing=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Stop early if secret is missing
        if: steps.secretcheck.outputs.missing == 'true'
        run: |
          echo "::notice title=Docs skipped::No OPENAI_API_KEY secret configured."

      - name: Checkout repo
        if: steps.secretcheck.outputs.missing == 'false'
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node (for consistency)
        if: steps.secretcheck.outputs.missing == 'false'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install jq
        if: steps.secretcheck.outputs.missing == 'false'
        run: sudo apt-get install -y jq

      - name: Collect repository context
        if: steps.secretcheck.outputs.missing == 'false'
        run: |
          set -euo pipefail
          FLAG=${{ github.event.inputs.include-template == 'true' && '--all' || '--user-only' }}
          node scripts/generate-docs.mjs $FLAG
          echo "Context size:"
          wc -c repo_context.txt || true

      - name: Generate README with OpenAI (scripted)
        if: steps.secretcheck.outputs.missing == 'false'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: bash scripts/ai-readme.sh

      - name: Build Wiki from code comments
        if: steps.secretcheck.outputs.missing == 'false'
        run: npm run docs:wiki

      - name: Format README and Wiki
        if: steps.secretcheck.outputs.missing == 'false'
        run: npm run fmt README.md docs/wiki

      - name: Prepare docs branch
        if: steps.secretcheck.outputs.missing == 'false'
        run: |
          if [ ! -s README.md ]; then
            echo "::error title=README fehlt::README.md wurde nicht erzeugt oder ist leer."
            exit 1
          fi
          set -euo pipefail
          BR="docs/generated-${{ github.run_id }}"
          git switch -c "$BR"
          git add README.md docs/wiki || true
          if git diff --cached --quiet; then
            echo "No doc changes detected – skipping PR."
            echo "skip_pr=true" >> "$GITHUB_OUTPUT"
          else
            echo "skip_pr=false" >> "$GITHUB_OUTPUT"
          fi
        id: prep

      - name: Create Pull Request
        if: steps.prep.outputs.skip_pr == 'false' && steps.secretcheck.outputs.missing == 'false'
        uses: peter-evans/create-pull-request@v6
        with:
          branch: docs/generated-${{ github.run_id }}
          commit-message: 'docs: auto-generate README + Wiki'
          title: 'Automatisch generierte Doku (README + Wiki)'
          body: 'Dieser PR wurde automatisch erstellt – bitte prüfen und mergen.'
          labels: 'automation, docs'
          signoff: false
